name: deploy-container

on:
  push:
    branches:
      - main # Aciona quando há push no branch 'main'
    paths:
      - "container/**" # Aciona quando há modificações na pasta 'container'

jobs:
  build:
    runs-on: ubuntu-latest # Define o ambiente onde a action será executada

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Baixa o código do repositório

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # Configura as credenciais AWS
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Chave de acesso AWS
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Chave secreta AWS
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }} # Região AWS

      - name: Install dependencies
        run: npm install # Instala as dependências (caso seja necessário)

      - name: Build the project
        run: npm run build # Gera os arquivos de build (caso seja necessário)

      - name: Sync build output to S3
        run: |
          aws s3 sync dist/ s3://$AWS_S3_BUCKET_NAME/container/latest --delete  # Faz o upload para o S3
        env:
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }} # Referencia o segredo AWS_S3_BUCKET_NAME
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} # Certifique-se de passar a região corretamente
