name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "container/**"

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "sa-east-1"
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Configure AWS CLI
        uses: shinyinc/action-aws-cli@v1.2

      - name: Sync build output to S3
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          aws s3 sync dist s3://$AWS_S3_BUCKET_NAME/container/latest
